services:
  db:
    image: postgres:18-alpine
    container_name: todo_api_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-todo}
    volumes:
      - todo_db:/var/lib/postgresql/data
    networks:
      - todo_api_network

  redis:
    image: redis:alpine
    container_name: todo_api_redis
    restart: always
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD:-redis_pass}
    ports:
      - "6379:6379"
    volumes:
      - todo_redis:/data
    networks:
      - todo_api_network

volumes:
  todo_db:
  todo_redis:

networks:
  todo_api_network:
    driver: bridge
